import React from 'react';
import {
  Landmark, Receipt, Tag, TrendingUp, LineChart, Briefcase, Home, Building2,
  ArrowLeftRight, Activity, Scale, Fuel, PiggyBank, Weight, Flame, Percent,
  Divide, Box, Cake, CalendarRange, HeartPulse, Sigma, CalendarClock,
  Search, Sun, Moon, X, ArrowRight, Mail, Menu,
  Wallet, ShieldCheck, BarChart3, Key, Target, Ruler, Droplet, Baby,
  Calculator, Shuffle, RefreshCw, Clock, Hourglass,
  CreditCard, ArrowUpRight, TrendingDown, Users, GitCompare, Zap, Car,
  Tags, Paintbrush, BedDouble, Coffee, Footprints, GraduationCap, ClipboardCheck,
  BookOpen,
  Hammer, PaintRoller, Grid3x3, Blocks, Truck, Layers, Bath, CookingPot, Triangle, HardHat,
  Package, Shirt, Coins, FlameKindling, Repeat, BatteryCharging, Siren, ChefHat, Utensils, PawPrint, Shield,
} from 'lucide-react';

const ICONS = {
  landmark: Landmark,
  receipt: Receipt,
  tag: Tag,
  'trending-up': TrendingUp,
  'line-chart': LineChart,
  briefcase: Briefcase,
  home: Home,
  building: Building2,
  'arrow-left-right': ArrowLeftRight,
  activity: Activity,
  scale: Scale,
  fuel: Fuel,
  'piggy-bank': PiggyBank,
  weight: Weight,
  flame: Flame,
  percent: Percent,
  divide: Divide,
  box: Box,
  cake: Cake,
  'calendar-range': CalendarRange,
  'heart-pulse': HeartPulse,
  sigma: Sigma,
  'calendar-clock': CalendarClock,
  search: Search,
  sun: Sun,
  moon: Moon,
  close: X,
  'arrow-right': ArrowRight,
  mail: Mail,
  menu: Menu,
  wallet: Wallet,
  'shield-check': ShieldCheck,
  'bar-chart-3': BarChart3,
  key: Key,
  target: Target,
  ruler: Ruler,
  droplet: Droplet,
  baby: Baby,
  calculator: Calculator,
  shuffle: Shuffle,
  'refresh-cw': RefreshCw,
  clock: Clock,
  hourglass: Hourglass,
  'credit-card': CreditCard,
  'arrow-up-right': ArrowUpRight,
  'trending-down': TrendingDown,
  users: Users,
  'git-compare': GitCompare,
  zap: Zap,
  car: Car,
  tags: Tags,
  paintbrush: Paintbrush,
  bed: BedDouble,
  coffee: Coffee,
  footprints: Footprints,
  'graduation-cap': GraduationCap,
  'clipboard-check': ClipboardCheck,
  'book-open': BookOpen,
  hammer: Hammer,
  'paint-roller': PaintRoller,
  'grid-3x3': Grid3x3,
  blocks: Blocks,
  truck: Truck,
  layers: Layers,
  bath: Bath,
  'cooking-pot': CookingPot,
  triangle: Triangle,
  'hard-hat': HardHat,
  package: Package,
  shirt: Shirt,
  coins: Coins,
  'flame-kindling': FlameKindling,
  repeat: Repeat,
  'battery-charging': BatteryCharging,
  siren: Siren,
  'chef-hat': ChefHat,
  utensils: Utensils,
  'paw-print': PawPrint,
  shield: Shield,
};

export default function Icon({ name, size = 20, strokeWidth = 1.75, className, ...rest }) {
  const Component = ICONS[name];
  if (!Component) return null;
  return <Component size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...rest} />;
}
